"""Regenerate the combined reading formats from the TXT sources.

  python tools/build_combined.py            write Software_Engineering_14_Week_Plan.md (+ .pdf when Chromium is available)
  python tools/build_combined.py --no-pdf
  python tools/build_combined.py --check    exit 1 when the Markdown or the PDF is stale

The TXT files are the single source. The Markdown and the PDF are derived reading copies
and carry a notice saying so; never edit them by hand. The PDF is produced through
Playwright's Chromium when the package is installed (pip install -r requirements-dev.txt;
python -m playwright install chromium); otherwise only the Markdown is written. A PDF build
records the SHA-256 of the Markdown it was built from in Software_Engineering_14_Week_Plan.pdf.built-from,
which is how --check knows the PDF is current without comparing PDF bytes.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plan_lib import ROOT, SUPPORT_FILES, WEEK_NUMBERS, read  # noqa: E402

ORDER = [SUPPORT_FILES[0]] + [f"week{n}.txt" for n in WEEK_NUMBERS] + SUPPORT_FILES[1:]
NOTICE = ("Derived file. Generated by tools/build_combined.py from the weekly and support TXT files, "
          "which are the only source. Edit those files and regenerate; do not edit this copy.")


def txt_to_blocks(text: str) -> list[tuple[str, str]]:
    """Return (kind, content) blocks: title, h2, h3, label, para."""
    lines = text.split("\n")
    blocks: list[tuple[str, str]] = []
    i = 0
    para: list[str] = []

    def flush():
        if para:
            blocks.append(("para", " ".join(para)))
            para.clear()

    while i < len(lines):
        line = lines[i]
        nxt = lines[i + 1] if i + 1 < len(lines) else ""
        if i == 0:
            blocks.append(("title", line.strip()))
        elif set(line.strip()) in ({"="}, {"-"}) and line.strip():
            pass
        elif nxt.strip() and set(nxt.strip()) == {"-"} and len(nxt.strip()) >= 3:
            flush()
            level = "h3" if re.match(r"^0\d\. ", line) or line.isupper() and not re.match(r"^\d{1,2}\. ", line) else "h2"
            blocks.append((level, line.strip()))
            i += 1
        elif not line.strip():
            flush()
        else:
            m = re.match(r"^([A-Z][A-Z ,/’'\-]+): (.+)$", line)
            if m and len(m.group(1)) < 60:
                flush()
                blocks.append(("label", f"{m.group(1)}: {m.group(2)}"))
            else:
                para.append(line.strip())
        i += 1
    flush()
    return blocks


def to_markdown(name: str, text: str) -> str:
    out = []
    for kind, content in txt_to_blocks(text):
        if kind == "title":
            out.append(f"# {content}")
        elif kind == "h2":
            out.append(f"## {content}")
        elif kind == "h3":
            out.append(f"### {content}")
        elif kind == "label":
            label, rest = content.split(": ", 1)
            out.append(f"**{label}:** {rest}")
        else:
            out.append(content)
        out.append("")
    return "\n".join(out)


def to_html(name: str, text: str) -> str:
    out = [f'<section id="{html.escape(Path(name).stem)}">']
    for kind, content in txt_to_blocks(text):
        c = html.escape(content)
        if kind == "title":
            out.append(f"<h1>{c}</h1>")
        elif kind == "h2":
            out.append(f"<h2>{c}</h2>")
        elif kind == "h3":
            out.append(f"<h3>{c}</h3>")
        elif kind == "label":
            label, rest = c.split(": ", 1)
            out.append(f"<p><strong>{label}:</strong> {rest}</p>")
        else:
            out.append(f"<p>{c}</p>")
    out.append("</section>")
    return "\n".join(out)


CSS = """
body{font-family:Georgia,'Times New Roman',serif;font-size:11pt;line-height:1.45;margin:0;color:#111}
section{page-break-before:always;padding:0 4mm}
section:first-of-type{page-break-before:auto}
h1{font-size:20pt;margin:0 0 6pt}h2{font-size:14pt;margin:14pt 0 4pt}h3{font-size:12pt;margin:10pt 0 3pt}
h1,h2,h3{break-after:avoid;page-break-after:avoid}p{orphans:3;widows:3}
p{margin:0 0 6pt}.notice{font-size:9pt;color:#555;border:1px solid #bbb;padding:4pt;margin-bottom:10pt}
@page{size:A4;margin:16mm}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--no-pdf", action="store_true")
    parser.add_argument("--check", action="store_true", help="exit 1 when the Markdown or the PDF is stale")
    args = parser.parse_args()
    texts = [(name, read(ROOT / name)) for name in ORDER if (ROOT / name).exists()]
    md = ["# Software Engineering: a 14-week visual lecture plan", "", f"> {NOTICE}", ""]
    md += [to_markdown(name, text) for name, text in texts]
    md_text = "\n".join(md)
    digest = hashlib.sha256(md_text.encode("utf-8")).hexdigest()
    md_path = ROOT / "Software_Engineering_14_Week_Plan.md"
    stamp_path = ROOT / "Software_Engineering_14_Week_Plan.pdf.built-from"
    if args.check:
        stale = []
        if not md_path.exists() or read(md_path) != md_text:
            stale.append(md_path.name)
        if not stamp_path.exists() or stamp_path.read_text(encoding="utf-8").strip() != digest:
            stale.append("Software_Engineering_14_Week_Plan.pdf")
        if stale:
            print(f"STALE {stale}: run python tools/build_combined.py")
            return 1
        print("OK combined plan copies are current")
        return 0
    md_path.write_text(md_text, encoding="utf-8")
    print(f"wrote {md_path}")
    if args.no_pdf:
        return 0
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        sync_playwright = None
    page_html = ("<!doctype html><html><head><meta charset='utf-8'><title>Software Engineering 14-week plan</title>"
                 f"<style>{CSS}</style></head><body><p class='notice'>{html.escape(NOTICE)}</p>"
                 + "\n".join(to_html(name, text) for name, text in texts) + "</body></html>")
    tmp = ROOT / "Software_Engineering_14_Week_Plan.derived.html"
    tmp.write_text(page_html, encoding="utf-8")
    pdf_path = ROOT / "Software_Engineering_14_Week_Plan.pdf"
    try:
        if sync_playwright is not None:
            with sync_playwright() as p:
                browser = p.chromium.launch()
                page = browser.new_page()
                page.goto(tmp.resolve().as_uri())
                page.pdf(path=str(pdf_path), format="A4", print_background=True, prefer_css_page_size=True,
                         display_header_footer=True, header_template="<span></span>",
                         footer_template='<div style="font-size:8px;width:100%;text-align:center;color:#555">'
                                         'Software Engineering - Instructor plan | '
                                         '<span class="pageNumber"></span> / <span class="totalPages"></span></div>')
                browser.close()
            stamp_path.write_text(digest + "\n", encoding="utf-8")
            print(f"wrote {pdf_path} (Playwright Chromium)")
        else:
            chrome = find_chrome()
            if not chrome:
                print("no Playwright and no Chrome found; PDF not regenerated "
                      "(pip install -r requirements-dev.txt; python -m playwright install chromium)")
                return 0
            import subprocess
            subprocess.run([chrome, "--headless=new", "--disable-gpu", "--no-pdf-header-footer",
                            f"--print-to-pdf={pdf_path}", tmp.resolve().as_uri()],
                           check=True, capture_output=True, timeout=300)
            stamp_path.write_text(digest + "\n", encoding="utf-8")
            print(f"wrote {pdf_path} (Chrome headless)")
    except Exception as exc:  # noqa: BLE001
        print(f"PDF not regenerated: {exc}")
    finally:
        tmp.unlink(missing_ok=True)
    return 0


def find_chrome() -> str | None:
    import os
    import shutil
    for name in ("chrome", "chrome.exe", "google-chrome", "chromium", "msedge"):
        found = shutil.which(name)
        if found:
            return found
    for base in (os.environ.get("PROGRAMFILES", ""), os.environ.get("PROGRAMFILES(X86)", ""), os.environ.get("LOCALAPPDATA", "")):
        for rel in (r"Google\Chrome\Application\chrome.exe", r"Microsoft\Edge\Application\msedge.exe"):
            cand = Path(base) / rel
            if base and cand.exists():
                return str(cand)
    return None


if __name__ == "__main__":
    raise SystemExit(main())
