"""Copy the teaching fixtures into the student site.

  python scripts/sync_fixtures.py            writes site/assets/fixtures/demo-fixtures.json and .js
  python scripts/sync_fixtures.py --check    exit 1 when the site copies are stale

plan/assets/demo-fixtures.json is the only source (AGENTS.md: fixtures are the only truth).
The decks load the .js form (window.CAMPUS_ROOMS_FIXTURES = {...}) with a plain <script> tag so
they also open from file:// without a fetch; the .json copy is kept beside it for readers.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "plan" / "assets" / "demo-fixtures.json"
OUT_DIR = ROOT / "site" / "assets" / "fixtures"


def render() -> tuple[str, str]:
    data = json.loads(SRC.read_text(encoding="utf-8-sig"))
    as_json = json.dumps(data, indent=1, ensure_ascii=False) + "\n"
    as_js = ("/* Generated by scripts/sync_fixtures.py from plan/assets/demo-fixtures.json. Do not edit. */\n"
             "window.CAMPUS_ROOMS_FIXTURES = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
    return as_json, as_js


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    as_json, as_js = render()
    targets = {OUT_DIR / "demo-fixtures.json": as_json, OUT_DIR / "demo-fixtures.js": as_js}
    if args.check:
        stale = [p.name for p, text in targets.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            print(f"STALE {stale}: run python scripts/sync_fixtures.py")
            return 1
        print("OK site fixtures are current")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for p, text in targets.items():
        p.write_text(text, encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
